version: '3.8'

services:

  gitlab-web:
    image: 'gitlab/gitlab-ce:13.2.1-ce.0'
    container_name: gitlab-web
    restart: always
    hostname: 'gitlab.localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab-web:8088'
    ports:
      - '8088:8088' # Same port 8088 here and in external_url !
      - '2222:2222'
    volumes:
      - "gitlab_web_data:/var/opt/gitlab"
      - "gitlab_web_logs:/var/log/gitlab"
      - "gitlab_web_config:/etc/gitlab"
    networks:
      - gitlab-network

  gitlab-runner:
    image: gitlab/gitlab-runner:ubuntu-v13.1.2
    container_name: gitlab-runner
    restart: always
    hostname: 'gitlab-runner'
    depends_on:
      - gitlab-web
    volumes:
      - 'gitlab_runner_config:/etc/gitlab-runner:Z'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - gitlab-network

networks:
  gitlab-network:
    name: gitlab-network

volumes:

  gitlab_web_data:
    driver: local
    driver_opts:
      type: nfs4
      o: "bind"
      device: "/home/vagrant/gitlab/volumes/gitlab-web/data"

  gitlab_web_logs:
    driver: local
    driver_opts:
      type: nfs4
      o: "bind"
      device: "/home/vagrant/gitlab/volumes/gitlab-web/logs"

  gitlab_web_config:
    driver: local
    driver_opts:
      type: nfs4
      o: "bind"
      device: "/home/vagrant/gitlab/volumes/gitlab-web/config"

  gitlab_runner_config:
    driver: local
    driver_opts:
      type: nfs4
      o: "bind"
      device: "/home/vagrant/gitlab/volumes/gitlab-runner/config"